---
name: "Groq-Go Code Review action"
description: "Automatic code review using groq-go"
inputs:
  groq_api_key:
    description: 'Groq API key'
    required: true
  diff_file:
    description: 'Generated diff file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Code review
      run: go run cmd/main.go
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
        DIFF_FILE: ${{ inputs.diff_file }}
      shell: bash
      working-directory: ${{ github.action_path }}
