---
name: "Groq-Go Code Review action"
description: "Automatic code review using groq-go"
inputs:
  groq_api_key:
    description: 'Groq API key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download go modules
      run: go mod download
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Generate diff
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git diff origin/${{ github.event.pull_request.base.ref }} > diff.txt

    - name: Code review
      run: go run cmd/main.go
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
      shell: bash
      working-directory: ${{ github.action_path }}
