---
name: "Groq-Go Code Review action"
description: "Automatic code review using groq-go"
inputs:
  groq_api_key:
    description: 'Groq API key'
    required: true
  diff_file:
    description: 'Generated diff file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Code review
      id: review
      run: go run cmd/main.go
      env:
        GROQ_API_KEY: ${{ inputs.groq_api_key }}
        DIFF_FILE: ${{ inputs.diff_file }}
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      working-directory: ${{ github.action_path }}

    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.review.outputs.REVIEW_COMMENT }}'
          })
